### ISSUE TITLE
add makefile

### ISSUE THREAD

**Issue by KewinLima** [KewinLima/discreta12BatimaeRobi#4]
adicionar makefile e editar o mesmo com o comando -lhpthread

**Comment by KewinLima** [comment]
Feito.

**Comment by drbeco** [comment]
a biblioteca vai na chave `LDLIBS` e não na `CFLAGS`.
- **CFLAGS**: flags para o compilador C (gcc)
- **CPPFLAGS**: flags para o pré-processador (C-Pré-Processor)
- **LDLIBS**: flags para o _linker_

**Comment by KewinLima** [comment]
Entendido, alis estava dando uma olhada no caderno e entrei exatamente para reabrir essa issues!
