### ISSUE TITLE
TAD's [ tipos abstratos de dados ]

### ISSUE THREAD

**Issue by KewinLima** [KewinLima/discreta12BatimaeRobi#9]
Adicionar as quais TAD's serão usadas..pilhas..listas..

**Comment by KewinLima** [comment]
Ok, usaremos pilhas nas transições.

**Comment by drbeco** [comment]
E é preciso listas para anotar todos os lugares e transições, não é? Vetores não são dinâmicos, ok? Só confirma para mim aqui e se quiser pode fechar novamente.

**Comment by KewinLima** [comment]
ok, usaremos de listas para armazenar os lugares e as transições.
